### ISSUE TITLE
Enums and other decls members have incorrect highlighting

### ISSUE THREAD

**Issue by rauhul** [jtbandes/swift-tmlanguage#10]
Firstly, thanks for maintaining this library!

I think a recent change broke how declaration members are rendered. If you take a look at this snippet from swift-mmio you can see the enum cases are highlighted incorrectly:
https://github.com/apple/swift-mmio/blob/496ae117d5993036d0862e407fca9ada4f4270e5/Tests/MMIOFileCheckTests/FileCheck.swift#L12-L15

<img width="406" alt="Screenshot 2023-12-15 at 8 24 47 PM" src="https://github.com/jtbandes/swift-tmlanguage/assets/9739930/109c2308-ba83-4aa5-8045-47eaf34d24e0">

**Comment by jtbandes** [comment]
Thanks for the report. There must be some changes I made that are not working with GitHub's highlighter, but are working fine with VS Code. 😢  

I'll try to look into these soon but unfortunately GitHub only updates their grammars to the latest version every few months, so it may be a while before it's fixed.

**Comment by jtbandes** [comment]
I believe this is an error with GitHub's highlighter; you can follow along at: https://github.com/github-linguist/linguist/issues/6668

**Comment by jtbandes** [comment]
The underlying issue with GitHub has been fixed. Sadly, GitHub is no longer using this tmLanguage grammar: https://github.com/github-linguist/linguist/issues/6668#issuecomment-1967867179

**Comment by rauhul** [comment]
Regardless of them switching over, truly thank you for keeping this grammar alive, it's been very helpful. I appreciate the time and effort you've put into making this :)
