### ISSUE TITLE
Highlighting breaks after Codable & Identifiable 

### ISSUE THREAD

**Issue by ktoso** [jtbandes/swift-tmlanguage#11]
In this file: 
https://github.com/apple/swift/pull/68861/files

The following problem appears:
![image](https://github.com/jtbandes/swift-tmlanguage/assets/120979/4461cddb-e6f3-45b1-9f6d-3e0cae165e2c)

it seems after the Codable & Identifiable, we lose highlighting for a while until we get a parameter type `Value` again which then works again

**Comment by jtbandes** [comment]
I believe this is an error with GitHub's highlighter; you can follow along at: https://github.com/github-linguist/linguist/issues/6668
