### ISSUE TITLE
`await tryFoo()` highlights as an error

### ISSUE THREAD

**Issue by rjmccall** [jtbandes/swift-tmlanguage#5]
The `await try` check needs to respect token boundaries.

**Comment by jtbandes** [comment]
We might be able to sneak this in just in time for GitHub's release tomorrow :)

**Comment by jtbandes** [comment]
Next release it is! https://github.com/github-linguist/linguist/pull/6603#issuecomment-1853176361

**Comment by rjmccall** [comment]
Thanks for the quick turnaround! Even if the integration will take a bit.
